"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const rsvpController_1 = require("../controllers/rsvpController");
const uploadMiddleware_1 = require("../middleware/uploadMiddleware");
const authMiddleware_1 = require("../middleware/authMiddleware");
const router = (0, express_1.Router)();
router.post("/upload-guest-excel", authMiddleware_1.authenticate, uploadMiddleware_1.upload.single("file"), rsvpController_1.addGuestFromFile);
router.get("/:eventId", authMiddleware_1.authenticate, rsvpController_1.getUserByEventId);
router.post("/addSingleGuest", authMiddleware_1.authenticate, rsvpController_1.addSingleGuest);
router.delete("/removeSingleGuest", authMiddleware_1.authenticate, rsvpController_1.removeSingleGuest);
router.put("/:eventId/:guestId", authMiddleware_1.authenticate, rsvpController_1.updateGuest);
router.post("/inviteAll", authMiddleware_1.authenticate, rsvpController_1.inviteAllGuest);
router.post("/rsvp/respond", rsvpController_1.responseInvite);
router.post("/sendReminder", authMiddleware_1.authenticate, rsvpController_1.sendReminder);
router.delete("/removeAllGuestOrVendor", authMiddleware_1.authenticate, rsvpController_1.removeAllGuestOrVendor);
router.get("/rsvp/validate", rsvpController_1.validateUrl);
exports.default = router;
